const DAYS = ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"];
const aliases = {"Lun.":"Lun","Mar.":"Mar","Mie.":"Mié","Mié.":"Mié","Jue.":"Jue","Vie.":"Vie","Sab.":"Sáb","Sáb.":"Sáb"};
const courses = window.COURSE_OPTIONS;
const saved = JSON.parse(localStorage.getItem("mi-horario-seleccion") || "[]");
let selectedIds = saved.filter((id) => courses.some((course) => course.id === id));
const courseCodes = [...new Set(courses.map((course) => course.code))].sort();
const courseColors = new Map(courseCodes.map((code, index) => [code, `hsl(${(index * 137.508) % 360} 62% 39%)`]));
const courseColor = (course) => courseColors.get(course.code);
const mode = (session) => session.modality.toLowerCase().includes("sincron") ? "virtual" : "presencial";
const hour = (text) => { const [h,m] = text.split(":").map(Number); return h + m / 60; };
const time = (value) => `${String(Math.floor(value)).padStart(2,"0")}:${String(Math.round((value % 1) * 60)).padStart(2,"0")}`;
function parse(course, session) { const match = session.schedule.match(/^(\S+)\s+(\d{2}:\d{2})\s+-\s+(\d{2}:\d{2})$/); return match && aliases[match[1]] ? {course,session,day:aliases[match[1]],start:hour(match[2]),end:hour(match[3])} : null; }
function save() { localStorage.setItem("mi-horario-seleccion", JSON.stringify(selectedIds)); }
function select(id) { selectedIds = selectedIds.includes(id) ? selectedIds.filter((value) => value !== id) : [...selectedIds,id]; save(); render(); }
function visibleCourses() { const query = document.querySelector("#search").value.trim().toLowerCase(); return (query ? courses.filter((course) => `${course.code} ${course.name} ${course.section}`.toLowerCase().includes(query)) : courses.slice(0,18)).slice(0,30); }
function renderCatalog() { const list = visibleCourses(); document.querySelector("#count").textContent = list.length ? `${list.length} resultado${list.length === 1 ? "" : "s"}` : "No encontré ese curso"; document.querySelector("#catalog").innerHTML = list.map((course) => `<article class="course" style="--course:${courseColor(course)}"><i class="course-swatch" aria-hidden="true"></i><div><small>${course.code} · SEC. ${course.section}</small><strong>${course.name}</strong><small>${course.sessions.length} sesiones · ${course.sessions[0].schedule}</small></div><button class="${selectedIds.includes(course.id) ? "remove" : ""}" data-id="${course.id}" aria-label="${selectedIds.includes(course.id) ? "Quitar" : "Agregar"} ${course.code} sección ${course.section}">${selectedIds.includes(course.id) ? "Quitar" : "+"}</button></article>`).join(""); document.querySelectorAll("#catalog button").forEach((button) => button.onclick = () => select(button.dataset.id)); }
function renderCalendar() { const selected = selectedIds.map((id) => courses.find((course) => course.id === id)).filter(Boolean); const blocks = selected.flatMap((course) => course.sessions.map((session) => parse(course,session)).filter(Boolean)); const overlaps = new Set(); const conflicts = [];
 for(let i=0;i<blocks.length;i++) for(let j=i+1;j<blocks.length;j++) if(blocks[i].course.id !== blocks[j].course.id && blocks[i].day === blocks[j].day && blocks[i].start < blocks[j].end && blocks[j].start < blocks[i].end) { overlaps.add(blocks[i]); overlaps.add(blocks[j]); conflicts.push({day:blocks[i].day,start:Math.max(blocks[i].start,blocks[j].start),end:Math.min(blocks[i].end,blocks[j].end),first:blocks[i].course,second:blocks[j].course}); }
 const calendar = document.querySelector("#calendar"); calendar.innerHTML = `<div class="calendar-wrap"><div class="calendar"><div class="time">${Array.from({length:16},(_,i)=>`<span>${String(i+7).padStart(2,"0")}:00</span>`).join("")}</div>${DAYS.map((day) => `<div><div class="day-head">${day}</div><div class="day">${blocks.filter((block) => block.day === day).map((block) => { const color = courseColor(block.course); const type = mode(block.session); const isConflict = overlaps.has(block); return `<article class="block ${isConflict ? "is-conflict" : ""}" style="--course:${color};--mode:${type === "virtual" ? "#5d3db5" : "#147449"};top:${(block.start-7)*60+4}px;height:${Math.max((block.end-block.start)*60-7,34)}px" title="${isConflict ? "Cruce de horario" : ""}"><strong>${block.course.code}</strong>${isConflict ? `<b class="conflict-tag">Cruce</b>` : ""}<em class="mode">${type}</em><span>${block.course.name}</span><small>${block.session.schedule}</small></article>`; }).join("")}</div></div>`).join("")}</div></div>`;
 const conflictAlert = document.querySelector("#conflict-alert"); const uniqueConflicts = [...new Map(conflicts.map((conflict) => [`${conflict.day}-${conflict.start}-${conflict.end}-${[conflict.first.id,conflict.second.id].sort().join("-")}`, conflict])).values()]; conflictAlert.hidden = uniqueConflicts.length === 0; conflictAlert.innerHTML = uniqueConflicts.length ? `<strong>⚠ ${uniqueConflicts.length} cruce${uniqueConflicts.length === 1 ? "" : "s"} de horario detectado${uniqueConflicts.length === 1 ? "" : "s"}</strong><ul>${uniqueConflicts.map((conflict) => `<li>${conflict.day} ${time(conflict.start)}–${time(conflict.end)}: <b>${conflict.first.code}</b> y <b>${conflict.second.code}</b></li>`).join("")}</ul>` : "";
 const sessionCount = selected.reduce((total, course) => total + course.sessions.length, 0); const summary = document.querySelector("#summary"); summary.hidden = selected.length === 0; summary.textContent = `${selected.length} curso${selected.length === 1 ? "" : "s"} · ${sessionCount} bloque${sessionCount === 1 ? "" : "s"}`; document.querySelector("#empty").hidden = selected.length > 0; document.querySelector("#clear").hidden = selected.length === 0; document.querySelector("#selected").hidden = selected.length === 0; document.querySelector("#selected-list").innerHTML = selected.map((course) => `<article class="selected-course" style="--course:${courseColor(course)}"><div><b><i class="course-swatch" aria-hidden="true"></i>${course.code} · SEC. ${course.section}</b><h3>${course.name}</h3><div class="sessions">${course.sessions.map((session)=>`<div><b>${session.schedule}</b> · ${session.location.replace("UTEC-BA ","")} · <span class="session-mode ${mode(session)}">${mode(session)}</span></div>`).join("")}</div></div><button class="remove" data-id="${course.id}">Quitar</button></article>`).join(""); document.querySelectorAll("#selected .remove").forEach((button) => button.onclick = () => select(button.dataset.id)); }
function render() { renderCatalog(); renderCalendar(); }
document.querySelector("#search").oninput = renderCatalog; document.querySelector("#clear").onclick = () => { selectedIds=[]; save(); render(); }; render();
