const DAYS = ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"];
const aliases = {"Lun.":"Lun","Mar.":"Mar","Mie.":"Mié","Mié.":"Mié","Jue.":"Jue","Vie.":"Vie","Sab.":"Sáb","Sáb.":"Sáb"};
const courses = window.COURSE_OPTIONS;
const saved = JSON.parse(localStorage.getItem("mi-horario-seleccion") || "[]");
let selectedIds = saved.filter((id) => courses.some((course) => course.id === id));
const hue = (id) => [...id].reduce((value, char) => (value * 31 + char.charCodeAt(0)) % 360, 0);
const mode = (session) => session.modality.toLowerCase().includes("sincron") ? "virtual" : "presencial";
const hour = (text) => { const [h,m] = text.split(":").map(Number); return h + m / 60; };
function parse(course, session) { const match = session.schedule.match(/^(\S+)\s+(\d{2}:\d{2})\s+-\s+(\d{2}:\d{2})$/); return match && aliases[match[1]] ? {course,session,day:aliases[match[1]],start:hour(match[2]),end:hour(match[3])} : null; }
function save() { localStorage.setItem("mi-horario-seleccion", JSON.stringify(selectedIds)); }
function select(id) { selectedIds = selectedIds.includes(id) ? selectedIds.filter((value) => value !== id) : [...selectedIds,id]; save(); render(); }
function visibleCourses() { const query = document.querySelector("#search").value.trim().toLowerCase(); return (query ? courses.filter((course) => `${course.code} ${course.name} ${course.section}`.toLowerCase().includes(query)) : courses.slice(0,18)).slice(0,30); }
function renderCatalog() { const list = visibleCourses(); document.querySelector("#count").textContent = list.length ? `${list.length} resultado${list.length === 1 ? "" : "s"}` : "No encontré ese curso"; document.querySelector("#catalog").innerHTML = list.map((course) => `<article class="course"><div><small>${course.code} · SEC. ${course.section}</small><strong>${course.name}</strong><small>${course.sessions.length} sesiones · ${course.sessions[0].schedule}</small></div><button class="${selectedIds.includes(course.id) ? "remove" : ""}" data-id="${course.id}">${selectedIds.includes(course.id) ? "Quitar" : "+"}</button></article>`).join(""); document.querySelectorAll("#catalog button").forEach((button) => button.onclick = () => select(button.dataset.id)); }
function renderCalendar() { const selected = selectedIds.map((id) => courses.find((course) => course.id === id)).filter(Boolean); const blocks = selected.flatMap((course) => course.sessions.map((session) => parse(course,session)).filter(Boolean)); const overlaps = new Set(); for(let i=0;i<blocks.length;i++) for(let j=i+1;j<blocks.length;j++) if(blocks[i].course.id !== blocks[j].course.id && blocks[i].day === blocks[j].day && blocks[i].start < blocks[j].end && blocks[j].start < blocks[i].end) { overlaps.add(blocks[i].course.id); overlaps.add(blocks[j].course.id); }
 const calendar = document.querySelector("#calendar"); calendar.innerHTML = `<div class="calendar-wrap"><div class="calendar"><div class="time">${Array.from({length:16},(_,i)=>`<span>${String(i+7).padStart(2,"0")}:00</span>`).join("")}</div>${DAYS.map((day) => `<div><div class="day-head">${day}</div><div class="day">${blocks.filter((block) => block.day === day).map((block) => { const color = `hsl(${hue(block.course.id)} 55% 40%)`; const type = mode(block.session); return `<article class="block" style="--course:${color};--mode:${type === "virtual" ? "#5d3db5" : "#147449"};top:${(block.start-7)*60+4}px;height:${Math.max((block.end-block.start)*60-7,34)}px"><strong>${block.course.code}</strong><em class="mode">${type}</em><span>${block.course.name}</span><small>${block.session.schedule}</small></article>`; }).join("")}</div></div>`).join("")}</div></div>`;
 document.querySelector("#empty").hidden = selected.length > 0; document.querySelector("#clear").hidden = selected.length === 0; document.querySelector("#selected").hidden = selected.length === 0; document.querySelector("#selected-list").innerHTML = selected.map((course) => `<article class="selected-course"><div><b>${course.code} · SEC. ${course.section}</b><h3>${course.name}</h3><div class="sessions">${course.sessions.map((session)=>`<div><b>${session.schedule}</b> · ${session.location.replace("UTEC-BA ","")} · ${mode(session)}</div>`).join("")}</div></div><button class="remove" data-id="${course.id}">Quitar</button></article>`).join(""); document.querySelectorAll("#selected .remove").forEach((button) => button.onclick = () => select(button.dataset.id)); }
function render() { renderCatalog(); renderCalendar(); }
document.querySelector("#search").oninput = renderCatalog; document.querySelector("#clear").onclick = () => { selectedIds=[]; save(); render(); }; render();
